# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4902da26269becdd712172c1eb4d7c2b9bbc97007c90e9d44da5085c3d5b8675439c6ee5398ea3b7baa84df3bd4fbca214cdc4237d296eaf975890ae82522c6d

test:
  secret_key_base: f66846917f38ca6223fee169f943dc871db22129d3f32a9f74e5a6e97b5a42f186a128b6b8494cc2e534d28da6fda8c5cbdc9fb4a72f42065a40c6663663c901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
